export interface userType {
    id: number,
    username: string,
    phone_number: string,
    email: string,
    status: number,
    created_at: string,
    updated_at: string,
    first_name: string,
    other_name: string,
    last_name: string,
    address: string,
    gender: string,
    city: string,
    postal_code: string,
    nationality: string,
    bvn: string,
    nin: string,
    drivers_licence_number: string,
    drivers_licence_photo: string,
    passport: string,
    email_notification: number,
    sms_notification: number,
    account_name: string,
    account_number: string,
    balance: string
}